version: "3.8"

services:
  db:
    image: mysql:8
    container_name: pos-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "33306:3306"
    volumes:
      - ./pos-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
